export default {
  data() {
    return {
      //弹框标题
      title: "",
      //多选
      checkList: [],
      //查询表单基础参数
      queryParams: [
        {
          type: "input",
          label: "名称",
          prop: "title",
          span: 6,
          attributes: {},
          on: {},
        },
        {
          type: "select",
          label: "类型",
          prop: "type",
          options: this.getDictData("menu_type"),
          span: 6,
          attributes: {},
          on: {},
        },
        {
          label: "状态",
          prop: "status",
          type: "select",
          options: this.getDictData("menu_status"),
          span: 6,
          attributes: {},
          on: {},
        },
      ],
      //表格数据
      tableData: [],
      //表列基础参数
      tableColumn: [
        {
          type: "selection",
          width: 55,
        },
        {
          label: "展开",
          prop: "show",
          fixed: "left",
        },
        {
          label: "名称",
          prop: "title",
          width: 150,
          sortable: true,
        },
        {
          label: "类型",
          prop: "type",
          width: 150,
          translation: "menu_type",
          sortable: true,
        },
        {
          label: "路径",
          prop: "path",
          width: 150,
          sortable: true,
        },
        {
          label: "组件名",
          prop: "name",
          width: 150,
          sortable: true,
        },
        {
          label: "组件路径",
          prop: "component",
          width: 200,
          sortable: true,
        },
        {
          label: "权限标识",
          prop: "permission",
          width: 150,
          sortable: true,
        },
        {
          label: "排序",
          prop: "sort",
          width: 150,
          sortable: true,
        },
        {
          label: "是否可见",
          prop: "visible",
          width: 150,
          sortable: true,
          translation: "isNo",
        },
        {
          label: "是否缓存",
          prop: "keepAlive",
          width: 150,
          sortable: true,
          translation: "isNo",
        },
        {
          label: "是否总是显示",
          prop: "alwaysShow",
          width: 150,
          sortable: true,
          translation: "isNo",
        },
        {
          label: "状态",
          prop: "status",
          width: 150,
          sortable: true,
          translation: "menu_status",
        },
        {
          label: "操作",
          type: "action",
          fixed: "right",
          width: 250,
        },
      ],
      //数据
      queryData: {
        id: null,
        parentId: null,
        title: null,
        name: null,
        path: null,
        type: null,
        component: null,
        permission: null,
        level: null,
        sort: null,
        visible: null,
        keepAlive: null,
        alwaysShow: null,
        icon: null,
        description: null,
        meta: null,
        status: null,
        remark: null,
        creator: null,
        updater: null,
        createTime: null,
        updateTime: null,
        isDeleted: null,
      },
      //新增/修改/详情数据
      formData: {
        id: null,
        parentId: null,
        name: null,
        title: null,
        path: null,
        type: 0,
        component: null,
        permission: null,
        level: null,
        sort: null,
        visible: null,
        keepAlive: null,
        alwaysShow: null,
        icon: null,
        description: null,
        meta: null,
        status: null,
        remark: null,
        creator: null,
        updater: null,
        createTime: null,
        updateTime: null,
        isDeleted: null,
      },
    };
  },
  computed: {
    //新增表单基础参数
    formParams() {
      const baseForm = [
        {
          type: "radio",
          label: "类型",
          prop: "type",
          span: 24,
          options: this.getDictData("menu_type"),
          attributes: {},
          on: {
            change() {},
          },
        },
      ];

      if (this.formData.type === "system") {
        return baseForm.concat([
          {
            type: "input",
            label: "应用名称",
            prop: "title",
            rules: [
              { required: true, message: "名称不能为空", trigger: "blur" },
            ],
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "应用编码",
            prop: "path",
            span: 6,
            rules: [
              { required: true, message: "路由路径不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "权限标识",
            prop: "permission",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "number",
            label: "排序",
            prop: "sort",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "状态",
            prop: "status",
            options: this.getDictData("menu_status"),
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "是否可见",
            prop: "visible",
            options: this.getDictData("isNo"),
            span: 6,
            attributes: {},
            on: {},
          },
        ]);
      } else if (this.formData.type === "directory") {
        return baseForm.concat([
          {
            type: "selectTree",
            label: "上级",
            prop: "parentId",
            span: 24,
            options: this.tableData,
            attributes: {
              label: "title",
              id: "id",
            },
            on: {},
          },
          {
            type: "input",
            label: "目录名称",
            prop: "title",
            rules: [
              { required: true, message: "名称不能为空", trigger: "blur" },
            ],
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "路径",
            prop: "path",
            span: 6,
            rules: [
              { required: true, message: "路由路径不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "权限标识",
            prop: "permission",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "number",
            label: "排序",
            prop: "sort",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "图标",
            prop: "icon",
            span: 12,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "状态",
            prop: "status",
            options: this.getDictData("menu_status"),
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "是否可见",
            prop: "visible",
            options: this.getDictData("isNo"),
            span: 6,
            attributes: {},
            on: {},
          },
        ]);
      } else if (this.formData.type === "menu") {
        return baseForm.concat([
          {
            type: "selectTree",
            label: "上级",
            prop: "parentId",
            span: 24,
            options: this.tableData,
            attributes: {
              label: "title",
              id: "id",
            },
            on: {},
          },
          {
            type: "input",
            label: "图标",
            prop: "icon",
            span: 12,
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "菜单名称",
            prop: "title",
            span: 6,
            rules: [
              { required: true, message: "名称不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "路由路径",
            prop: "path",
            span: 6,
            rules: [
              { required: true, message: "路由路径不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "组件名",
            prop: "name",
            span: 6,
            rules: [
              { required: true, message: "组件名不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "组件路径",
            prop: "component",
            span: 6,
            rules: [
              { required: true, message: "组件路径不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "权限标识",
            prop: "permission",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "number",
            label: "排序",
            prop: "sort",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "状态",
            prop: "status",
            options: this.getDictData("menu_status"),
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "是否可见",
            prop: "visible",
            options: this.getDictData("isNo"),
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "是否缓存",
            prop: "keepAlive",
            options: this.getDictData("isNo"),
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "是否总是显示",
            prop: "alwaysShow",
            options: this.getDictData("isNo"),
            span: 6,
            attributes: {},
            on: {},
          },
        ]);
      } else if (this.formData.type === "button") {
        return baseForm.concat([
          {
            type: "selectTree",
            label: "上级",
            prop: "parentId",
            span: 24,
            options: this.tableData,
            attributes: {
              label: "title",
              id: "id",
            },
            on: {},
          },
          {
            type: "input",
            label: "按钮名称",
            prop: "title",
            span: 6,
            rules: [
              { required: true, message: "名称不能为空", trigger: "blur" },
            ],
            attributes: {},
            on: {},
          },
          {
            type: "input",
            label: "权限标识",
            prop: "permission",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "number",
            label: "排序",
            prop: "sort",
            span: 6,
            attributes: {},
            on: {},
          },
          {
            type: "radio",
            label: "状态",
            prop: "status",
            options: this.getDictData("menu_status"),
            span: 6,
            attributes: {},
            on: {},
          },
        ]);
      }
    },
  },
};
